            var x = [
              990,
              2969,
              256,
              2848,
              736,
              386,
              2571,
              712,
              2775,
              2387,
              1487,
              804,
              655,
              2301,
              1203,
              2725,
              1947,
              2347,
              1931,
              1095,
              1210,
              2392,
              1543,
              2313,
              2549,
              274,
              2805,
              2741,
              2864,
              1175,
              2547,
              865,
              1470,
              1375,
              1769,
              1757,
              2106,
              2034,
              2583,
              1950,
              1252,
              1012,
              2195,
              2363,
              529,
              2453,
              2430,
              678,
              2511,
              1630,
              2751,
              205,
              918,
              2265,
              1999,
              2322,
              474,
              792,
              2863,
              1063,
              73,
              2377,
              919,
              262,
              2224,
              1297,
              961,
              496,
              3,
              2982,
              2518,
              1180,
              2564,
              9,
              2359,
              1738,
              1100,
              2404,
              1134,
              353,
              1152,
              1800,
              765,
              542,
              525,
              267,
              991,
              734,
              2487,
              1800,
              1518,
              2957,
              2343,
              1534,
              861,
              352,
              1771,
              134,
              1591,
              2904,
              2866,
              639,
              1040,
              672,
              1624,
              2764,
              715,
              1681,
              679,
              177,
              2899,
              1724,
              135,
              1954,
              1341,
              656,
              2407,
              229,
              1446,
              2724,
              2164,
              64,
              265,
              1967,
              537,
              1478,
              1372,
              558,
              2656,
              1678,
              1404,
              2943,
              1240,
              2260,
              1645,
              1131,
              2904,
              588,
              2214,
              1992,
              450,
              645,
              141,
              2736,
              2748,
              1347,
              831,
              1916,
              2347,
              1527,
              1891,
              134,
              336,
              1746,
              1512,
              221,
              2928,
              815,
              515,
              2650,
              2679,
              2953,
              1358,
              2691,
              2844,
              1878,
              1357,
              2837,
              595,
              2026,
              258,
              895,
              1007,
              1918,
              2572,
              1373,
              838,
              1235,
              1572,
              1578,
              2002,
              1618,
              2688,
              74,
              1628,
              1165,
              1419,
              1967,
              2660,
              2467,
              724,
              1522,
              430,
              1608,
              2630,
              580,
              2575,
              835,
              872,
              1502,
              985,
              1477,
              2998,
              2430,
              2348,
              2958,
              2808,
              50,
              2509,
              962,
              810,
              1786,
              2667,
              2500,
              2796,
              1161,
              2687,
              642,
              2826,
              1340,
              588,
              1433,
              726,
              879,
              1528,
              754,
              844,
              2932,
              1897,
              1789,
              647,
              2341,
              315,
              1341,
              1730,
              524,
              1113,
              1037,
              1994,
              1225,
              2355,
              2105,
              1778,
              1268,
              1583,
              1720,
              471,
              211,
              1650,
              352,
              2557,
              830,
              672,
              722,
              617,
              1929,
              611,
              431,
              1073,
              650,
              753,
              2940,
              2040,
              2075,
              1153,
              1642,
              1807,
              2994,
              2351,
              1202,
              2872,
              2320,
              1294,
              2935,
              1924,
              871,
              2093,
              1131,
              1105,
              80,
              213,
              2935,
              652,
              2043,
              514,
              1189,
              2557,
              1079,
              2344,
              840,
              2371,
              1293,
              2191,
              799,
              173,
              1160,
              1554,
              2101,
              1419,
              2008,
              1749,
              581,
              324,
              1264,
              1734,
              2116,
              2145,
              100,
              718,
              903,
              154,
              1823,
              1559,
              1727,
              831,
              2940,
              2887,
              2466,
              1306,
              1243,
              878,
              1876,
              1011,
              6,
              2669,
              2422,
              68,
              556,
              135,
              1669,
              351,
              1086,
              404,
              846,
              1220,
              2721,
              876,
              1241,
              319,
              1275,
              2849,
              2979,
              1370,
              769,
              2968,
              2457,
              1031,
              368,
              1210,
              2265,
              2456,
              2603,
              2693,
              131,
              2946,
              2589,
              1048,
              1177,
              47,
              2423,
              3000,
              619,
              227,
              2636,
              2052,
              2213,
              874,
              90,
              2943,
              1133,
              1008,
              2372,
              1055,
              1152,
              177,
              1750,
              1138,
              1548,
              1706,
              2297,
              537,
              2843,
              1431,
              544,
              759,
              1590,
              2111,
              2426,
              1835,
              744,
              2796,
              2961,
              2275,
              525,
              1960,
              2417,
              1068,
              211,
              589,
              2277,
              1648,
              472,
              2755,
              719,
              2544,
              2756,
              991,
              1798,
              1394,
              1120,
              1689,
              1045,
              2332,
              1999,
              1255,
              2954,
              834,
              2932,
              1889,
              1020,
              172,
              348,
              1301,
              2105,
              2651,
              1053,
              908,
              1078,
              237,
              680,
              2572,
              920,
              2799,
              171,
              1551,
              1995,
              2395,
              1905,
              2900,
              1449,
              2251,
              454,
              2565,
              53,
              1700,
              2078,
              785,
              2993,
              702,
              533,
              2650,
              1997,
              2379,
              525,
              2145,
              992,
              1534,
              1563,
              1880,
              1851,
              1750,
              2002,
              2329,
              396,
              2387,
              1069,
              2374,
              1769,
              633,
              23,
              1753,
              1511,
              2314,
              1757,
              132,
              1649,
              2385,
              270,
              939,
              788,
              2636,
              162,
              2209,
              1635,
              2881,
              121,
              1280,
              566,
              2661,
              645,
              1133,
              856,
              1440,
              875,
              2963,
              2353,
              2269,
              1398,
              1879,
              961,
              385,
              2613,
              300,
              759,
              2146,
              933,
              2408,
              1977,
              1074,
              1545,
              1006,
              437,
              467,
              818,
              1830,
              2263,
              1046,
              2994,
              186,
              203,
              2023,
              517,
              674,
              2101,
              779,
              1074,
              178,
              639,
              484,
              1854,
              2938,
              2147,
              724,
              1491,
              822,
              1706,
              2401,
              2815,
              87,
              1605,
              792,
              183,
              2571,
              74,
              1053,
              2125,
              2992,
              1864,
              1881,
              1383,
              1247,
              2550,
              101,
              91,
              190,
              178,
              878,
              2616,
              974,
              1606,
              1401,
              294,
              2407,
              1719,
              825,
              2713,
              968,
              1136,
              2455,
              626,
              1851,
              452,
              506,
              1238,
              2352,
              1804,
              503,
              171,
              1161,
              544,
              1498,
              2001,
              375,
              1993,
              934,
              973,
              2819,
              566,
              1793,
              132,
              1255,
              2877,
              1180,
              37,
              822,
              725,
              1809,
              952,
              216,
              33,
              2477,
              1822,
              1595,
              1023,
              2057,
              1384,
              2367,
              2234,
              1955,
              2973,
              1480,
              526,
              955,
              2942,
              850,
              2418,
              587,
              2165,
              2448,
              2330,
              453,
              2030,
              2917,
              45,
              700,
              2028,
              1471,
              28,
              2132,
              1422,
              2880,
              2421,
              659,
              2020,
              2895,
              1478,
              460,
              2533,
              462,
              2174,
              337,
              474,
              77,
              385,
              713,
              1777,
              2016,
              2450,
              2379,
              2130,
              2645,
              422,
              2890,
              262,
              2528,
              1438,
              1633,
              442,
              2554,
              1917,
              1961,
              1886,
              2871,
              1755,
              1984,
              2762,
              79,
              2329,
              2836,
              1443,
              1623,
              2238,
              833,
              779,
              2297,
              1050,
              1575,
              2455,
              1817,
              1681,
              1655,
              2261,
              1194,
              450,
              1615,
              2629,
              1952,
              888,
              444,
              1615,
              2023,
              2032,
              1336,
              1645,
              2396,
              300,
              1157,
              2755,
              155,
              208,
              17,
              2420,
              1129,
              1475,
              418,
              2455,
              2626,
              1873,
              2819,
              2170,
              30,
              2742,
              551,
              877,
              1863,
              2069,
              1477,
              938,
              1654,
              1962,
              853,
              43,
              1510,
              1365,
              2939,
              853,
              2033,
              1520,
              2209,
              164,
              1347,
              2866,
              1402,
              2543,
              2092,
              1974,
              788,
              1462,
              377,
              2253,
              1061,
              1961,
              797,
              699,
              2226,
              2690,
              100,
              361,
              267,
              309,
              1392,
              2734,
              1603,
              1687,
              2400,
              27,
              2855,
              1901,
              957,
              383,
              1429,
              2319,
              1863,
              2409,
              2871,
              2509,
              224,
              788,
              504,
              2224,
              2470,
              16,
              1094,
              1412,
              2023,
              2654,
              2328,
              2644,
              337,
              1988,
              2114,
              479,
              2064,
              2242,
              2231,
              666,
              1219,
              20,
              2815,
              2030,
              408,
              1593,
              2361,
              1475,
              359,
              2059,
              410,
              2253,
              1837,
              1712,
              78,
              558,
              346,
              1568,
              1118,
              1884,
              2517,
              1680,
              67,
              2076,
              1686,
              967,
              626,
              887,
              396,
              2799,
              529,
              28,
              16,
              158,
              720,
              2791,
              690,
              1357,
              108,
              1353,
              2171,
              697,
              1640,
              2791,
              539,
              2808,
              1045,
              511,
              891,
              206,
              2436,
              2352,
              149,
              121,
              1673,
              1785,
              243,
              1506,
              1746,
              1357,
              1414,
              1685,
              1543,
              2750,
              1288,
              450,
              581,
              1280,
              243,
              2621,
              262,
              527,
              387,
              18,
              1364,
              219,
              306,
              574,
              2270,
              755,
              2211,
              810,
              2529,
              1264,
              393,
              1521,
              98,
              2964,
              1088,
              2092,
              1827,
              722,
              2276,
              2684,
              1884,
              2503,
              2209,
              952,
              2348,
              2369,
              2803,
              63,
              440,
              2343,
              544,
              608,
              20,
              1410,
              946,
              80,
              1336,
              2427,
              320,
              916,
              1052,
              221,
              2248,
              695,
              159,
              35,
              1214,
              2871,
              2396,
              1661,
              2440,
              1083,
              2414,
              2119,
              2477,
              143,
              2846,
              11,
              1475,
              636,
              1818,
              2001,
              2392,
              2169,
              920,
              2779,
              1099,
              1831,
              2620,
              590,
              2524,
              643,
              766,
              526,
              2385,
              2197,
              2855,
              280,
              595,
              105,
              1853,
              2862,
              2961,
              2371,
              2022,
              895,
              2699,
              2321,
              1538,
              1469,
              889,
              724,
              1059,
              163,
              132,
              758,
              89,
              1823,
              1469,
              1066,
              2289,
              2236,
              1806,
              1769,
              606,
              867,
              6,
              2313,
              515,
              979,
              2425,
              947,
              1008,
              1094,
              726,
              2844,
              851,
              1518,
              698,
              1436,
              64,
              320,
              350,
              2518,
              1852,
              191,
              413,
              87,
              119,
              348,
              897,
              2067,
              1000,
              2750,
              1062,
              2652,
              2149,
              1940,
              1910,
              836
            ];
            var text = document.getElementsByClassName("percent-txt");
            var barr = document.getElementsByClassName("percent-bar");
            for (let i = 0; i <= text.length; i++) {
              const d = new Date();
              var date = d.getUTCDate();
              var day = d.getUTCDay() + 1;
              var year = d.getUTCFullYear();
              var month = d.getUTCMonth() + 1;
              var hour = d.getUTCHours();
              var min = d.getMinutes();
              if (min < 30) {
                min = 1;
              } else {
                min = 2;
              }
              var xx = day + year * month * date;
              xx = Math.pow(xx, hour * min);
              xx = xx * x[i];
              if (
                i == 0 ||
                i == 8 ||
                i == 79 ||
                i == 104 ||
                i == 4 ||
                i == 5 ||
                i == 35 ||
                i == 77 ||
                i == 1 ||
                i == 18 ||
                i == 96
              ) {
                xx = xx % 27;
                xx += 65;
              } else {
                xx = xx % 83;
                xx += 8;
              }
              var percentTxt = text[i];
              var bar = barr[i];
              percentTxt.innerHTML = xx + "%";
              $(barr[i])
                .attr("aria-valuenow", xx)
                .css("width", xx + "%");
              if (xx < 30) {
                bar.classList.add("red");
              } else if (xx > 70) {
                bar.classList.add("green");
              } else {
                bar.classList.add("yellow");
              }
            }</script>
          <script>
            var button = document.getElementById("1generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('1ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("2generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('2ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("3generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('3ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("4generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('4ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("5generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('5ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("6generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('6ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("7generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('7ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("8generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('8ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("9generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('9ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("10generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('10ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("11generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('11ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("12generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('12ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("13generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('13ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("14generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('14ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("15generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('15ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("16generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('16ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("17generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('17ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("18generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('18ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("19generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('19ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("20generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('20ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("21generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('21ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("22generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('22ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("23generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('23ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("24generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('24ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("25generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('25ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("26generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('26ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("27generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('27ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("28generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('28ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("29generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('29ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("30generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('30ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("31generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('31ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("32generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('32ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("33generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('33ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("34generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('34ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("35generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('35ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("36generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('36ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("37generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('37ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("38generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('38ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("39generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('39ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("40generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('40ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("41generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('41ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("42generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('42ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("43generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('43ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("44generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('44ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("45generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('45ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("46generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('46ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("47generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('47ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("48generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('48ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("49generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('49ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("50generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('50ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("51generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('51ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("52generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('52ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("53generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('53ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("54generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('54ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("55generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('55ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("56generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('56ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("57generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('57ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("58generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('58ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("59generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('59ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("60generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('60ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("61generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('61ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("62generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('62ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("63generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('63ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("64generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('64ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("65generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('65ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("66generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('66ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("67generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('67ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("68generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('68ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("69generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('69ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("70generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('70ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("71generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('71ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("72generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('72ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("73generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('73ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("74generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('74ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("75generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('75ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("76generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('76ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("77generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('77ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("78generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('78ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("79generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('79ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("80generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('80ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("81generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('81ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("82generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('82ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("83generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('83ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("84generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('84ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("85generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('85ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("86generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('86ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("87generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('87ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("88generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('88ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("89generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('89ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("90generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('90ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("91generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('91ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("92generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('92ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("93generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('93ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("94generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('94ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("95generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('95ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("96generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('96ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("97generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('97ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("98generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('98ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("99generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('99ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("100generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('100ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("101generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('101ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("102generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('102ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("103generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('103ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("104generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('104ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("105generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('105ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("106generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('106ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("107generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('107ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("108generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('108ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("109generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('109ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("110generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('110ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("111generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('111ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("112generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('112ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("113generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('113ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("114generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('114ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("115generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('115ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("116generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('116ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("117generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('117ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("118generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('118ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("119generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('119ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("120generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('120ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("121generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('121ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("122generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('122ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("123generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('123ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("124generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('124ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("125generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('125ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("126generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('126ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("127generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('127ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("128generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('128ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("129generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('129ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("130generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('130ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("131generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('131ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("132generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('132ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("133generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('133ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("134generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('134ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("135generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('135ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("136generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('136ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("137generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('137ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("138generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('138ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("139generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('139ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("140generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('140ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("141generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('141ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("142generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('142ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("143generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('143ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("144generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('144ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("145generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('145ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("146generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('146ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("147generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('147ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("148generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('148ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("149generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('149ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("150generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('150ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("151generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('151ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("152generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('152ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("153generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('153ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("154generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('154ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("155generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('155ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("156generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('156ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("157generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('157ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("158generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('158ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("159generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('159ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("160generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('160ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("161generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('161ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("162generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('162ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("163generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('163ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("164generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('164ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("165generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('165ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("166generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('166ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("167generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('167ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("168generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('168ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("169generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('169ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("170generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('170ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("171generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('171ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("172generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('172ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("173generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('173ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("174generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('174ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("175generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('175ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("176generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('176ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("177generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('177ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("178generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('178ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("179generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('179ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("180generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('180ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("181generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('181ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("182generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('182ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("183generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('183ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("184generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('184ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("185generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('185ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("186generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('186ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("187generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('187ranNum'); el.innerHTML = randomNum; }
            var button = document.getElementById("188generate"); button.onclick = function generate() { var randomNum = Math.floor((Math.random() * 79) + 20); var el = document.getElementById('188ranNum'); el.innerHTML = randomNum; }


          </script>
